### ISSUE TITLE
translation missing: views.pagination.truncate on products admin page

### ISSUE THREAD

**Issue by craft37** [shoprgem/shopr#32]
Fixed by addin this lines in locale:

```
  views:
    pagination:
      first: "&laquo; Першая"
      last: "Апошняя &raquo;"
      previous: "&lsaquo; Назад"
      next: "Далей &rsaquo;"
      truncate: "..."
```
